version: '3.2'
services:

  autolab-proxy:
    image: duckietown/dt-autolab-proxy:daffy-${ARCH}
    container_name: autolab-proxy
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  autolab-localization:
    image: duckietown/dt-autolab-localization:daffy-${ARCH}
    container_name: autolab-localization
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
