version: '3.2'
services:

  deadreckoning:
    image: ${REGISTRY}/duckietown/dt-core:daffy-${ARCH}
    container_name: core
    restart: unless-stopped
    network_mode: host
    command: dt-launcher-deadreckoning
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

