version: '3.2'
services:

  core:
    image: duckietown/dt-core:ente-${ARCH}
    container_name: core
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
